# Objective: Generate a PCA plot of PC1 and PC2 from RNAseq data of young and old iPSC lines
# Extended Data Figure 3b
# Use vst data generated by DESeq2 core analysis: DESeq2_analysis_DEGs_VST_values_iPSC

###########################################################################################
# Required packages

######################################################################################################################################
# Set working directory
setwd('~/Dropbox/Code_checking_SM/For_Brittany/Figures/PCA/PCA_iPSC_in_vitro/')

# Upload data
load("~/Dropbox/Code_checking_SM/For_Brittany/Core_Analysis/iPSC_in_vitro/DESeq2_iPSC_vst_values.Rda")
colnames(v.data)

# Change the names so that it reflects their corresponding RE propenisty 
colnames(v.data) <- c(rep("Young",5), 
                      "Bad","Bad",
                      "Good", "Good","Good","Good")
colnames(v.data)

# PCA using prcomp function
e.pca <- prcomp(t(v.data), scale = T)

# get the precentage for each component
summary(e.pca)
# Importance of components:
#                           PC1     PC2     PC3     PC4    PC5      PC6      PC7      PC8      PC9     PC10      PC11
# Standard deviation     62.4981 48.5431 40.5042 39.8625 37.665 28.00691 27.36902 24.38016 22.47891 22.34192 3.382e-13
# Proportion of Variance  0.2782  0.1678  0.1168  0.1132  0.101  0.05586  0.05334  0.04233  0.03598  0.03555 0.000e+00
# Cumulative Proportion   0.2782  0.4460  0.5628  0.6759  0.777  0.83281  0.88615  0.92847  0.96445  1.00000 1.000e+00

# find the color code for orange and darkblue
col2rgb("orange")   # 255, 165, 0
col2rgb("darkblue") # 0, 0, 139

# Make PCA plot based PC1 and PC2
pdf("PCA_DESeq2_vst_RNAseq_iPSC_PC1-2.no.label.pdf", width =4.3, height =5 )
  par(mar=c(4.1,4.1,6,1), xpd=TRUE)
  plot(e.pca$x[,c(1,2)],
       pch = 15,  
       xlab = 'PC1 (28%)', 
       ylab = 'PC2 (17%)',
       cex.lab = 1.5, 
       col = "white",
       cex=0.6,
       xlim = c(-70,180),
       ylim = c(-100,60)
       ) 
  points(e.pca$x[grep("Young", colnames(v.data)) ,c(1,2)],  pch=17, cex=3, 
         col=rgb(red=255,green=165,blue=0, alpha = 204, maxColorValue = 255))
  
  points(e.pca$x[grep("Good", colnames(v.data)) ,c(1,2)],pch=17, cex=3, 
         col=rgb(red=0,green=0,blue=139, alpha = 140, maxColorValue = 255))
  
  points(e.pca$x[grep("Bad", colnames(v.data)) ,c(1,2)],pch=17, cex=3, 
         col=rgb(red=0,green=0,blue=139, alpha = 204, maxColorValue = 255))
  
  legend("topright",c("Young","Good Old", "Bad Old"), inset=c(0,-0.33),horiz=T,
  col=c("orange","Lightblue","darkblue"), text.col=c("orange","Lightblue","darkblue"), pch=c(17,17,17), cex = 1.5 , pt.cex=3)
dev.off()

