# Objective: Visualize expression of CKs that are higher in old plasma 
#
# Use vst values generated by DESeq2_analysis_DEGs_VST_values_invivo_fibs_180805

###########################################################################################
# Need the following package
library('pheatmap')    # v1.0.10
library("DESeq2")      # 1.20.0
sessionInfo()
###########################################################################################
# Set working directory
setwd('~/Dropbox/Code_checking_SM/For_Brittany/Figures/Heatmaps/EDF6d_heatmap_DEGs_THY1/')

# Load vst values from DESeq2
load("~/Dropbox/Code_checking_SM/For_Brittany/Core_Analysis/THY1_Fibroblast_in_vivo/DESeq2_THY1_in_vivo_vst_values.Rda")

# Make a Young/Old signature expression based on all the genes that are significantly lower/hihger with age
# Upload DEG data from DESeq2
load("~/Dropbox/Code_checking_SM/For_Brittany/Core_Analysis/THY1_Fibroblast_in_vivo/DESeq2_DEG_THY1_in_vivo_all_genes.Rda")
# Make it into a data frame
genes<- as.data.frame(resOrdered)
# Extract all DEGs that gow up with afe 
deg <- genes[which(genes$padj < 0.05 & abs(genes$log2FoldChange) > 0.58),] #597

v.data.deg <- v.data[which(row.names(v.data) %in% row.names(deg)),]
  
pdf("Heatmap_THY1_in_vivo_fibroblasts_180805.pdf", width =4.3, height =5, onefile=F  )
pheatmap(v.data.deg, 
         cluster_col=T, 
         cluster_row=T, 
         scale="row", 
         annotation_legend=TRUE,
         clustering_distance_cols="correlation", 
         clustering_method="complete",
         fontsize_col=6,
         fontsize_row=8,
         show_rownames=F,
         show_colnames=T,
         fontface="bold",
         treeheight_col=20,
         treeheight_row=0,
         cellwidth = 10, 
         cellheight = NA,
         border_color = NA,
         color = colorRampPalette(c("darkblue","dodgerblue4", "white","brown1","darkred"))(100))
dev.off()
