# Objective: Generate a PCA plot of PC1&PC2 and PC2&PC3 from RNAseq data of good and bad old fibroblast cultures 
# Figure 2f
# Use batch-corrected vst data generated by DESeq2 core analysis: DESeq2_analysis_DEGs_VST_values.R
###########################################################################################
# Required packages

######################################################################################################################################
# Set working directory
setwd('~/Dropbox/Code_checking_SM/For_Brittany/Figures/PCA/PCA_good_bad_old_fibs/')

# Upload data
load("~/Dropbox/Code_checking_SM/For_Brittany/Core_Analysis/Fibroblast_in_vitro/DESeq2_vst_corrected_values.Rda")
colnames(v.data)

# Exrtact the old cultures 
v.data.old <- v.data[,grep("Fib_29", colnames(v.data))]
colnames(v.data.old)

# Change the names so that it reflects their corresponding RE propenisty 
colnames(v.data.old) <- c("Bad","Good", "Bad","Good",
                          "Bad", "Good","Bad",
                          "Good", "Good","Bad")
colnames(v.data.old)

# PCA using prcomp function
e.pca <- prcomp(t(v.data.old), scale = T)

# get the precentage for each component
summary(e.pca)
# Importance of components:
#                           PC1     PC2     PC3     PC4     PC5      PC6      PC7      PC8      PC9      PC10
# Standard deviation     52.3743 50.7243 40.8924 39.4153 37.8502 36.23247 33.56387 31.61200 29.94909 5.855e-13
# Proportion of Variance  0.1917  0.1798  0.1168  0.1086  0.1001  0.09174  0.07872  0.06983  0.06268 0.000e+00
# Cumulative Proportion   0.1917  0.3715  0.4883  0.5969  0.6970  0.78876  0.86749  0.93732  1.00000 1.000e+00

# find the color code for orange and darkblue
col2rgb("orange")   # 255, 165, 0
col2rgb("darkblue") # 0, 0, 139

# Make PCA plot based PC1 and PC2
pdf("PCA_DESeq2_good_bad_old_Fib_PC1-2.no.label.pdf", width =4.3, height =5 )
  par(mar=c(4.1,4.1,6,1), xpd=TRUE)
  plot(e.pca$x[,c(1,2)],
       pch = 15,  
       xlab = 'PC1 (19%)', 
       ylab = 'PC2 (18%)',
       cex.lab = 1.5, 
       col = "white",
       cex=0.6,
       xlim = c(-110,90),
       ylim = c(-110,60)
       ) 
  points(e.pca$x[grep("Good", colnames(v.data.old)) ,c(1,2)],pch=17, cex=3, 
         col=rgb(red=0,green=0,blue=139, alpha = 140, maxColorValue = 255))
  
  points(e.pca$x[grep("Bad", colnames(v.data.old)) ,c(1,2)],pch=17, cex=3, 
         col=rgb(red=0,green=0,blue=139, alpha = 204, maxColorValue = 255))
  
  legend("topright",c("Young","Good Old", "Bad Old"), inset=c(0,-0.33),horiz=T,
  col=c("orange","Lightblue","darkblue"), text.col=c("orange","Lightblue","darkblue"), pch=c(17,17,17), cex = 1.5 , pt.cex=3)
dev.off()



# Make PCA plot based PC2 and PC3
pdf("PCA_DESeq2_good_bad_old_Fib_PC2-3.no.label.pdf", width =4.3, height =5 )
par(mar=c(4.1,4.1,6,1), xpd=TRUE)
plot(e.pca$x[,c(2,3)],
     pch = 15,  
     xlab = 'PC2 (18%)', 
     ylab = 'PC3 (12%)',
     cex.lab = 1.5, 
     col = "white",
     cex=0.6
     #xlim = c(-100,120),
     #ylim = c(-60,80)
) 
points(e.pca$x[grep("Good", colnames(v.data.old)) ,c(2,3)],pch=17, cex=3, 
       col=rgb(red=0,green=0,blue=139, alpha = 140, maxColorValue = 255))

points(e.pca$x[grep("Bad", colnames(v.data.old)) ,c(2,3)],pch=17, cex=3, 
       col=rgb(red=0,green=0,blue=139, alpha = 204, maxColorValue = 255))

legend("topright",c("Young","Good Old", "Bad Old"), inset=c(0,-0.33),horiz=T,
       col=c("orange","Lightblue","darkblue"), text.col=c("orange","Lightblue","darkblue"), pch=c(17,17,17), cex = 1.5 , pt.cex=3)
dev.off()

