# Objective: Generate a PCA plot of PC1 and PC2 from RNAseq data of young and old cells
# Figure 2b
# Use batch-corrected vst data generated by DESeq2 core analysis
###########################################################################################
# Required packages

######################################################################################################################################
# Set working directory
setwd('~/Dropbox/Code_checking_SM/For_Brittany/Figures/PCA/CAREFUL_PCA_fibroblast_in vitro/')

# Upload data
load("~/Dropbox/Code_checking_SM/For_Brittany/Core_Analysis/Fibroblast_in_vitro/DESeq2_vst_corrected_values.Rda")
colnames(v.data)

# Change the names so that it reflects their corresponding RE propenisty 
colnames(v.data) <- c(rep("Young",8), 
                      "Bad","Good", "Bad","Good",
                      "Bad", "Good","Bad",
                      "Good", "Good","Bad")
colnames(v.data)

# PCA using prcomp function
e.pca <- prcomp(t(v.data), scale = T)

# get the precentage for each component
summary(e.pca)
# Importance of components:
#                         PC1     PC2     PC3     PC4      PC5      PC6    PC7      PC8      PC9    PC10     PC11     PC12     PC13     PC14     PC15      PC16     PC17     PC18
# Standard deviation     55.341 41.6419 38.6432 34.5661 31.43161 29.29025 27.278 26.37877 24.96769 24.3679 23.05823 22.62491 21.29661 21.03624 19.56099 7.948e-13 4.84e-13 2.78e-13
# Proportion of Variance  0.214  0.1212  0.1043  0.0835  0.06904  0.05995  0.052  0.04863  0.04356  0.0415  0.03715  0.03577  0.03169  0.03092  0.02674 0.000e+00 0.00e+00 0.00e+00
# Cumulative Proportion   0.214  0.3352  0.4395  0.5231  0.59208  0.65204  0.704  0.75266  0.79622  0.8377  0.87487  0.91064  0.94234  0.97326  1.00000 1.000e+00 1.00e+00 1.00e+00

# find the color code for orange and darkblue
col2rgb("orange")   # 255, 165, 0
col2rgb("darkblue") # 0, 0, 139

# Make PCA plot based PC1 and PC2
pdf("PCA_DESeq2_BATCH_Corrected_vst_RNAseq_Fib_PC1-2.no.label.pdf", width =4.3, height =5 )
  par(mar=c(4.1,4.1,6,1), xpd=TRUE)
  plot(e.pca$x[,c(1,2)],
       pch = 15,  
       xlab = 'PC1 (21%)', 
       ylab = 'PC2 (12%)',
       cex.lab = 1.5, 
       col = "white",
       cex=0.6,
       xlim = c(-100,120),
       ylim = c(-60,80)) 
  points(e.pca$x[grep("Young", colnames(v.data)) ,c(1,2)],  pch=17, cex=3, 
         col=rgb(red=255,green=165,blue=0, alpha = 204, maxColorValue = 255))
  
  points(e.pca$x[grep("Good", colnames(v.data)) ,c(1,2)],pch=17, cex=3, 
         col=rgb(red=0,green=0,blue=139, alpha = 140, maxColorValue = 255))
  
  points(e.pca$x[grep("Bad", colnames(v.data)) ,c(1,2)],pch=17, cex=3, 
         col=rgb(red=0,green=0,blue=139, alpha = 204, maxColorValue = 255))
  
  legend("topright",c("Young","Good Old", "Bad Old"), inset=c(0,-0.33),horiz=T,
  col=c("orange","Lightblue","darkblue"), text.col=c("orange","Lightblue","darkblue"), pch=c(17,17,17), cex = 1.5 , pt.cex=3)
dev.off()

